version: '2'

services:
  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: local_test_elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=es_dataserver
      - node.name=es01
      - TAKE_FILE_OWNERSHIP=true 
    mem_limit: 1G
    ports:
      - '9200:9200'