name: Publish Docker image

on:
  push:
    tags:
      - '*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ vars.DOCKERHUB_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: sync indexers configuration
        uses: adrianjost/files-sync-action@v2.1.0
        with:
          FILE_PATTERNS: |
            ^indexers/notebook/entrypoint\.py$
            ^indexers/dataset/repositories/(?!(common\.py|__init__\.py)$).+$
          TARGET_REPOS: |
            DevOps-Group20/kb-indexer-backend
          TARGET_ROOT: |
            indexconfig/
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FILES }}
