name: Files Sync Action

on: 
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
      - uses: adrianjost/files-sync-action@v2.1.0
        with:
          FILE_PATTERNS: |
            ^indexers/notebook/entrypoint\.py$
            ^indexers/dataset/repositories/(?!(common\.py|__init__\.py)$).+$
          TARGET_REPOS: |
            DevOps-Group20/kb-indexer-backend
          TARGET_ROOT: |
            indexconfig/
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FILES }}

